### ISSUE TITLE
runner isn't exiting with 1 or 0 properly after run on Circle

### ISSUE THREAD

**Issue by awatson1978** [DispatchMe/meteor-mocha-phantomjs#28]
Hi there,
Decided to give the latest unit testing a spin on Circle CI, and got everything launched and running; however, it seems the reporter isn't exiting with a 1 or 0.  And it just sits there.............

![screen shot 2016-09-01 at 2 22 08 pm](https://cloud.githubusercontent.com/assets/675910/18181261/0763642e-7050-11e6-9230-1a940af3708c.png)

My `.circle.yml` file is as follows:

``` yml
machine:
  # Add some environment variables
  environment:
    CIRCLE_ENV: test
    CXX: g++-4.8
    DISPLAY: :99.0
    NPM_PREFIX: /home/ubuntu/nvm/v0.10.33
    INITIALIZE: true
    METEOR_OFFLINE_CATALOG: true
    NODE_ENV: development

## Customize dependencies
dependencies:
  cache_directories:
    - "~/.meteor" # relative to the user's home directory

  pre:
    - mkdir -p ${HOME}/.meteor
    - if [ ! -e ${HOME}/.meteor/meteor ]; then curl https://install.meteor.com | /bin/sh; else echo "Meteor seems to be cached"; fi;
    - sudo ln -s $HOME/.meteor/meteor /usr/bin/meteor

## Customize test commands
test:
  pre:
    - meteor update --release METEOR@1.3.4.1
    - sleep 60
    - meteor --version
    - meteor npm install
    - "meteor run":
          background: true
    - sleep 180
  override:
    - meteor npm run-script phantom-mocha
```

And my `package.json` file contains the following script:

```
{
  "name": "fhir-demo",
  "version": "1.0.0",
  "scripts": {
    "phantom-mocha": "meteor test --once --driver-package dispatch:mocha-phantomjs --port 3030",
  }
}
```

If anybody points me in the right direction, I'll be happy to make a fix and submit a pull request.
