### ISSUE TITLE
Phantom Version

### ISSUE THREAD

**Issue by firrae** [DispatchMe/meteor-mocha-phantomjs#9]
Hey there,

So I've been trying to use DroneCI to build and test my project but I keep having an issue where I get the following result for the client tests:

```
--------------------------------
I20160427-03:57:18.141(0)? ----- RUNNING CLIENT TESTS -----
I20160427-03:57:18.142(0)? --------------------------------
I20160427-03:57:18.142(0)? 
I20160427-03:57:18.142(0)? /root/.meteor/packages/dispatch_phantomjs-tests/.0.0.4.chn5yb++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
I20160427-03:57:18.143(0)? All client and server tests finished!
I20160427-03:57:18.143(0)? 
I20160427-03:57:18.143(0)? --------------------------------
I20160427-03:57:18.144(0)? SERVER FAILURES: 0
I20160427-03:57:18.144(0)? CLIENT FAILURES: 127
```
To be clear, this works 100% on my MacBook Pro, only on my private DroneCI server do I get this error using cpuguy83/debian:jessie docker image as the base. Here is my full drone configuration:
```
clone:
  path: github.com/name/project

build:
  test:
    image: cpuguy83/debian:jessie
    commands:
      - apt-get update
      - apt-get install curl -y
      - curl https://install.meteor.com | /bin/sh
      - meteor npm install
      - meteor npm test
```
I'm not 100% sure what I'm doing wrong, if someone could point me in the proper direction it would be greatly appreciated.
